### PR TITLE
Install Foreman locally instead

### PR DESCRIPTION
**Pull request by basicfeatures**

### CODE REVIEW

**Comment by dhh** [comment]
What is this looking to achieve?

**Comment by basicfeatures** [comment]
Added security by not compromising the root of ones system.

You can see my full demo here: https://github.com/basicfeatures/openbsd-rails 👍

**Comment by dhh** [comment]
Okay, that's not how we generally use gems in Rails. Fine to want to do something else, but this is only triggered if foreman isn't available. So you can install foreman with those provisions in advance, and this won't get triggered.

**Comment by basicfeatures** [comment]
Thanks for getting back at me. Sounds good 👍

**Pull request closed without merging**
